name: output project
on:
  push:
    branches:
      - main
  workflow_dispatch:
  jobs:
    output:
      runs-on: ubuntu-latest
      steps:
        - name: get info
          run: echo "${{(tojson(github))}}" > info.json


        